name:                ErrorReportingParsers
version:             0.1.0.0
github:              "pcrama/ErrorReportingParsers"
license:             BSD3
author:              "Philippe Crama"
maintainer:          "pcfeb0009@gmx.com"
copyright:           "2018"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            experiment,parser

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/pcrama/ErrorReportingParsers#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

executables:
  ErrorReportingParsers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ErrorReportingParsers

tests:
  ErrorReportingParsers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ErrorReportingParsers
    - hspec
    - HUnit
