name:                synctests
version:             0.1.0.0
github:              "pcrama/haskell-scribbling"
license:             BSD3
author:              "Philippe Crama"
maintainer:          "pcfeb0009@gmx.com"
copyright:           "2018 Philippe Crama"

extra-source-files:
- README.org

description:         Please see the README on GitHub at <https://github.com/pcrama/synctests#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.1
- filepath >= 1.4
- directory >= 1.3
- time >= 1.6

library:
  source-dirs: src

executables:
  synctests-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - synctests

tests:
  synctests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - synctests
